#!/usr/bin/bash
# msg=$(
# cat << EOF
# Format: '<type>([optional scope]): [<ticket id>]<description>'
# Example: 'fix: [DEV-123] correct the huddle event completion'
# EOF
# )

# if ! grep -oE '^(feat|fix|refactor|perf|style|test|docs|build|ops|chore).*: \[[[:alnum:]]+-[[:alnum:]]+\] [[:alnum:]]+' $1; then
#     echo -e "\033[0;31mERROR!!! Please follow commit convention.\033[0m"
#     echo "$msg"
#     exit 1
# fi